name: Build and Ship

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    name: build-${{ matrix.os }}-${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}

    strategy:
      fail-fast: false
      matrix:
        cc: ["gcc", "clang"]
        os: ["ubuntu-latest"]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Install Dependencies
      run: sudo apt-get install -y libjansson-dev libsdl2-dev libsdl2-image-dev lua5.4-dev 

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Debug .

    - name: Build
      run: cmake --build .

#    - name: Test
#      run: ctest

    - name: Create rpgng Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.cc }}-rpgng-master
        path: bin/*
        if-no-files-found: error
        retention-days: 1

  build-macos-latest-clang:
    runs-on: macos-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install Dependencies
        run: brew install lua jansson sdl2 sdl2_image

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug .

      - name: Build
        run: cmake --build .

#      - name: Test
#        run: ctest

      - name: Create rpgng Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-clang-rpgng-master
          path: bin/*
          if-no-files-found: error
          retention-days: 1

  build-windows-latest-msvc:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install Dependencies
        run: vcpkg install jansson:x64-windows lua:x64-windows sdl2:x64-windows sdl2-image:x64-windows

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        run: cmake --build . --config Debug

#      - name: Test
#        run: ctest -C Debug

      - name: Create rpgng Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-latest-msvc-rpgng-master
          path: bin/*
          if-no-files-found: error
          retention-days: 1

  Formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format-15

      - name: Run formatting
        run: find . -name '*.h' -o -name '*.c' | xargs clang-format-15 -style=file -i

      - name: Check formatting
        run: git diff --exit-code

  Pages:
    needs: [build-linux, build-windows-latest-msvc, build-macos-latest-clang]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y graphviz doxygen libjansson-dev libsdl2-dev libsdl2-image-dev lua5.4-dev 

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DRPGNG_DOCS=ON .

      - name: Build Docs
        run: cmake --build .

      - name: Create Docs Artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: docs/html/

      - name: Publish Documentation
        uses: actions/deploy-pages@v1.2.2
